BOT_TOKEN = "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
DB_TABLE_NAME = "MyTelegramWalletBot"
SECRETS_TABLE_NAME = "MyTelegramWalletBotSecrets"
DB_ENCRYPTION_KEY_ALIAS = "alias/wavestelegramwalletbot"
NODE_URL = "https://nodes.wavesplatform.com"
NET_ID = "mainnet"
